The syncer has beed updated to check the PersistentVolumeReclaimPolic…
infracloudio/vcluster pull request #1
Opened 2022-08-09 13:28 UTC by maheshbaliga

The syncer has been updated to check the PersistentVolumeReclaimPolicy before deleting the PV. If the PersistentVolumeReclaimPolicy is not 'Delete', the PV is not deleted and its status is updated. Before this code change, irrespective of the PersistentVolumeReclaimPolicy, the PV was getting deleted.

The syncer_test has been modify with the following changes:
1. Added a default PersistentVolumeReclaimPolicy field to the existing test case objects, since now the syncer checks for the PersistentVolumeReclaimPolicy field to take further action. 
2. Added a new test case for updating the virtual PV status with the new status from the physical PV status.

Issue 1 & 2 is fixed with this code. This fix will work when SC (based on dynamic provisioning), PVC & POD are created on the VC.

2022-08-10 08:08 UTC, samkulkarni20 commented on pkg/controllers/resources/persistentvolumes/syncer.go
> +			updatedPV.Status = *pPersistentVolume.Status.DeepCopy()
@maheshbaliga 
1. What is the physical volume here? host cluster PV / Cloud Provider volume?
2. Are we sure that the physical volume has the correct status & we can copy status from that to PV in vCluster?

2022-08-10 08:08 UTC, samkulkarni20 commented on pkg/controllers/resources/persistentvolumes/syncer.go
> +		if vPersistentVolume.Spec.PersistentVolumeReclaimPolicy == corev1.PersistentVolumeReclaimDelete {
@maheshbaliga Does it consider the "Default" reclaim policies for PV? Seems it has different defaults, depending on if the PV is created manually or dynamically. See: https://pkg.go.dev/k8s.io/api/core/v1#PersistentVolumeSpec

2022-08-10 09:21 UTC, ApsTomar requested changes

2022-08-10 09:21 UTC, ApsTomar commented on pkg/controllers/resources/persistentvolumes/syncer.go
> +		} else {
If you've put a return statement in the end of if-block, then else statement is not required. You can put "else code" outside the condition block.

2022-08-19 10:36 UTC, maheshbaliga commented
New PR has been raised with new code changes.

2022-08-19 10:36 UTC, closed without merging