Allow syncer to omit taints that have enforced tolerations
infracloudio/vcluster pull request #2
Opened 2022-08-09 13:42 UTC by neogopher

**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind bugfix

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 

Tolerations are enforced on a pod level, which works nicely for Deployment and StatefulSet kinds. However, having synched nodes with a custom taint on every node results in 0 pods running for a given DaemonSet as the DaemonSet controller evaluates the DaemonSet with no toleration on it (the toleration would get synced on the pod level).

With this fix, Node syncer will not sync those taints from the host node, for which the vcluster has enforced tolerations defined. Subsequently, these nodes will be available to the Daemonset Controller for scheduling the pods.

2022-08-10 08:22 UTC, ApsTomar requested changes

2022-08-10 08:22 UTC, ApsTomar commented on pkg/controllers/resources/nodes/syncer.go
> +			if err == nil {
What happens when the error is not nil? How are we handling any error that occurs when toleration.ParseToleration() function is called?

2022-08-10 08:22 UTC, ApsTomar commented on pkg/controllers/resources/nodes/translate.go
> +
We don't need to provide official documentation link. As a comment, we only provide the info about what or why we have implemented certain code or if there is any special case like you mentioned below.

2022-08-16 12:56 UTC, neogopher reviewed
All suggested changes were addressed.

2022-08-16 12:56 UTC, neogopher commented on pkg/controllers/resources/nodes/translate.go
> +
ok Noted. How can I remove the comments from this commit.

2022-08-16 12:56 UTC, neogopher commented on pkg/controllers/resources/nodes/syncer.go
> +			if err == nil {
I need to check. However, this same function is present in the existing code for Pod Syncer. I will have to check with Oleg for the same.

2022-08-16 12:56 UTC, neogopher commented on pkg/controllers/resources/nodes/syncer.go
> +			if err == nil {
I have analysed the code and found that this same error check is already done when vcluster starts in start.go and if it finds any error that time it will error out. Syncer component reuses the parseToleration again put this time it only uses tolerations directly and doesn't bother about the err because it was already checked before.

2022-08-16 12:56 UTC, neogopher commented on pkg/controllers/resources/nodes/syncer.go
> +			if err == nil {
Had a discussion with Abhay about the above observation. For this PR, it is safe to go ahead with this change as it mimics existing code from pod syncer. However, given an opportunity, I will try to understand the motive behind the same from Oleg/Fabian and would be the desired side effect of the error check if we implement the error check.

2022-08-18 08:01 UTC, samkulkarni20 approved these changes

2022-08-18 08:29 UTC, ApsTomar approved these changes

2022-08-18 08:52 UTC, merged